- name: install and run nginx
  hosts: web
  become: yes # root access
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: installed
  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes