# - name: uninstall nginx
#   hosts: web
#   become: yes
#   tasks: 
#     - name: uninstall nginx server
#       ansible.builtin.package:
#         name: nginx
#         state: absent
#     - name: stop the nignx
#       ansible.builtin.service:
#         name: nginx
#         state: stopped


- name: install and start apache server
  hosts: web
  become: yes
  tasks:
    - name: install apache server
      ansible.builtin.package:
        name: apache server
        state: installed
    - name: start the apache server
      ansible.builtin.service:
        name: apache server
        state: started