- name: PLAY1
  hosts: localhost
  connection: localhost # managing its own node
  tasks:
    - name: PLAY1 and TASK1
      ansible.builtin.debug:
        msg: "hello from PLAY1 and TASK1"

- name: PLAY2
  hosts: localhost
  connection: localhost # managing its own node
  tasks:
    - name: PLAY2 and TASK1
      ansible.builtin.debug:
        msg: "hello from PLAY2 and TASK1"














# - name: install and start apache server
#   hosts: web
#   become: yes
#   tasks:
#     - name: install apache server
#       ansible.builtin.package:
#         name: apache server
#         state: installed
#     - name: start the apache server
#       ansible.builtin.service:
#         name: apache server
#         state: started