- name: variables
  hosts: localhost
  connection: localhost
  vars: # play level variables, global variables
    COURSE: "DevOps with AWS"
    DURATION: 120hrs
    TRAINER: SAI
  tasks:
    - name: print the variables
      vars: # task level variables accessible only within this task. task variables van ovveride play level varibales
        COURSE: Ansible
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
  
    - name: print the variables1
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"

