- name: variables
  hosts: localhost
  connection: localhost
  vars: # play level variables
    COURSE: "Devops with aws"
    DURATION: "120hrs"
    TRAINER: "Sai"
  tasks:
  - name: print the variables
    vars: # task level variables
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
  
  - name: print variables1
     ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"