- name: variables from files
  hosts: localhost
  connection: localhost
  vars_files:
  - course.yaml
  tasks:
    - name: print course information
      ansible.builtin.debug:
       msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"