- name: variables from files
  hosts: local
  connection: local
  tasks:
  - name: 
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
