- name: check value is less than 10 or not
  hosts: localhost
  connection: localhost
  vars:
    given_number: 15
  tasks:
  - name: print if the number is less than 10
    ansible.builtin.debug:
      msg: "Given number {{ given_number }} is less than 10"
    when: given_number > 10
  
  - name: print if the number is less than are equal to 10
    ansible.builtin.debug:
      msg: "Given number {{ given_number }} is less than are equal to 10"
    when: given_number <= 10