- name: filters
  hosts: localhost
  connection: localhost
  tasks:
    - name: handle undefined variable
      ansible.builtin.debug:
        msg: "hello {{ person | default('sai')}}"

    - name: convert string to list
      vars:
        fruits: "apple, banana, orange" # string 
      ansible.builtin.debug:
        msg: "{{ fruits | split(',') }}"

    - name: convert map into list
      vars:
        course: # map or dictionary
          name: ansible
          duartion: 10hrs
          trainer: sai
      ansible.builtin.debug:
          msg: "course information {{ course | dict2items}}"

    - name: convert list into map
      vars:
        course:
        - {'key': 'name', 'value': 'ansible'}
        - {'key': 'duration', 'value': '10hrs'}
        - {'key': 'trainer', 'value': 'sai'}
      ansible.builtin.debug:
          msg: "course information {{ course | items2dict }}"