- name: filters
  hosts: localhost
  connection: localhost
  tasks:
    - name: handle undefined variable
      ansible.builtin.debug:
        msg: "hello {{ person | default('sai')}}"

    - name: convert string to list
      vars:
        fruits: "apple, banana, orange" # string 
      ansible.builtin.debug:
        msg: "{{ fruits | split(',') }}"