- name: filters
  hosts: localhost
  connection: localhost
  tasks:
    - name: handle undefined variable
      ansible.builtin.debug:
        msg: "hello {{ person | default('sai')}}"

    - name: convert string to list
      vars:
        fruits: "apple, banana, orange" # string 
      ansible.builtin.debug:
        msg: "{{ fruits | split(',') }}"

    - name: convert map into list
      vars:
        course: # map or dictionary
          name: ansible
          duartion: 10hrs
          trainer: sai
      ansible.builtin.debug:
          msg: "course information {{ course | dict2items}}"

    - name: convert list into map
      vars:
        course:
        - {'key': 'name', 'value': 'ansible'}
        - {'key': 'duration', 'value': '10hrs'}
        - {'key': 'trainer', 'value': 'sai'}
      ansible.builtin.debug:
          msg: "course information {{ course | items2dict }}"

    - name: convert upper to lower
      vars:
        name: "Sai Krishna"
      ansible.builtin.debug:
        msg: "hello {{ name | lower }}"

    - name: convert lower to upper
      vars:
        name: "Sai Krishna"
      ansible.builtin.debug:
        msg: "hello {{ name | upper }}"

    - name: print min and max 
      vars:
        number: [16.30,45,6,7,110000,330000]
      ansible.builtin.debug:
        msg: "min: {{ number | min }} max: {{ number | max }}"

    - name: valid ip address or not
      vars:
        ip: "255.255.266.255"
      ansible.builtin.debug:
        msg: "{{ ip |ansible.utils.ipaddr }}"