- name: create ec2 and r53 records
  hosts: localhost
  connection: localhost
  vars:
    subnet_id: subnet-0270c21a623755744
    sg_id: sg-01076ba01e673e877 
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    instances:
    - mysql
    - frontend
    - backend
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_id: "{{ instance_type }}"
    loop: "{{ instances }}"
    
