- name: nignx installation
  hosts: all
  become: yes
  serial: 2
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: run nginx
    ansible.biuiltin.service:
      name: nginx
      state: started